import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { unlockForQA } from './access-helper.mjs';
const browser = await chromium.launch({ headless: true });
await mkdir('test-results', { recursive: true });
const errors = [];
const page = await browser.newPage();
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
const check = (condition, message) => { if (!condition) throw new Error(message); };
for (const [width, height] of [[320,568], [360,800], [375,812], [390,844], [393,852], [412,915], [430,932], [768,1024], [1024,768], [1280,720], [1366,768], [1440,900], [1920,1080]]) {
 await page.setViewportSize({ width, height });
 await page.goto(process.env.BASE_URL || 'http://localhost:3000');
 await unlockForQA(page);
 await page.locator('h1').waitFor();
 await page.waitForTimeout(1500);
 await page.screenshot({ path: `test-results/intro-${width}.png` });
 check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Intro overflow ${width}`);
 await page.getByRole('button', { name: 'открыть', exact: true }).click();
 await page.locator('.photo-album').waitFor();
 await page.waitForTimeout(1700);
 check(await page.locator('.phrase-dots span').count() === 5, 'Five phrase indicators');
 check(!await page.locator('.story').innerText().then(t => /Ваааань|дуешься|бусинки|Нормальный такой/.test(t)), 'Removed copy');
 check(await page.locator('.memory-3 .handwritten').innerText() === 'тут мы миленькие', 'Photo caption');
 check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Story overflow ${width}`);
 const first = page.locator('.memory').first();
 await first.click();
 await page.getByRole('dialog').waitFor();
 check(await page.locator('.lightbox-close').evaluate(el => document.activeElement === el), 'Initial dialog focus');
 await page.keyboard.press('Shift+Tab');
 check(await page.locator('.lightbox-next').evaluate(el => document.activeElement === el), 'Modal focus trap');
 await page.getByRole('button', { name: 'Следующее фото' }).click();
 check(await page.locator('.lightbox-caption').innerText().then(t => t.includes('2 из 6')), 'Next photo');
 await page.keyboard.press('ArrowLeft');
 await page.keyboard.press('Escape');
 await page.getByRole('dialog').waitFor({ state: 'hidden' });
 check(await first.evaluate(el => document.activeElement === el), 'Gallery focus restored');
 await page.getByRole('button', { name: 'открыть письмо', exact: true }).first().click();
 await page.waitForTimeout(1200);
 check(await page.locator('#personal-letter').getAttribute('aria-hidden') === 'false', 'Letter open');
 check(await page.locator('#personal-letter .signature').innerText() === 'Твой лапулик ♡', 'Letter signature');
 const geometry = await page.evaluate(() => {
  const letter = document.querySelector('#personal-letter').getBoundingClientRect();
  const signature = document.querySelector('#personal-letter .signature').getBoundingClientRect();
  const seal = document.querySelector('.wax-seal').getBoundingClientRect();
  return { fits: letter.left >= 0 && letter.right <= innerWidth && signature.bottom <= letter.bottom, sealClear: seal.top > signature.bottom };
 });
 check(geometry.fits && geometry.sealClear, `Readable unobstructed letter ${width}`);
 await page.locator('.letter-section').screenshot({ path: `test-results/letter-${width}.png` });
 await page.getByRole('button', { name: 'сложить письмо', exact: true }).first().click();
 const targets = await page.locator('button:visible').evaluateAll(nodes => nodes.map(n => ({ name: n.getAttribute('aria-label') || n.textContent, rect: n.getBoundingClientRect() })).filter(n => n.rect.width < 44 || n.rect.height < 44).map(n => n.name));
 check(targets.length === 0, `Small touch targets ${width}: ${targets}`);
 for (let i = 0; i < 3; i++) { await page.getByRole('button', { name: 'нажми сюда, Писюня' }).click(); await page.waitForTimeout(500); }
 check(await page.locator('.surprise h2').innerText().then(t => t.includes('ЛЮБЛЮ')), 'Surprise');
 await page.getByRole('button', { name: 'Включить музыку' }).click();
 check(await page.getByRole('status').innerText() === 'Сегодня тихо. Только мы.', 'Missing music');
 await page.locator('.final-heart').click({ clickCount: 3 });
 check(await page.getByRole('status').innerText() === 'ну всё, оно теперь твоё', 'Heart secret');
 await page.getByRole('button', { name: 'начать сначала' }).click();
 await page.waitForTimeout(900);
 check(await page.locator('.story').count() === 0, 'Restart');
 check(await page.locator('.open-button').evaluate(el => document.activeElement === el), 'Restart focus');
 console.log(`PASS ${width}x${height}: opening, overflow, gallery, keyboard, letter, surprise, sound, secret, restart`);
}
await page.emulateMedia({ reducedMotion: 'reduce' });
await page.goto(process.env.BASE_URL || 'http://localhost:3000');
await unlockForQA(page);
await page.getByRole('button', { name: 'открыть', exact: true }).click();
await page.locator('.things-static').waitFor();
check(await page.locator('.things-static h3').count() === 5, 'Reduced motion content');
await page.route('**/photos/*.jpg', route => route.fulfill({ status: 404, body: '' }));
await page.reload();
await page.locator('.photo-missing').first().waitFor();
console.log('PASS reduced motion and missing photographs');
const relevant = errors.filter(e => !e.includes('404') && !e.includes('net::ERR'));
console.log('Runtime errors:', JSON.stringify(relevant));
check(relevant.length === 0, 'Browser errors');
await browser.close();

